baseurl: "/"
title: "Stackbit Azimuth Theme"
init_js: "assets/js/init.js"
page_load_js: "assets/js/main.js"
params:
  palette: blue
  header:
    title: Azimuth
    logo_img: images/logo.png
    has_nav: true
    menu:
      actions:
        - label: Sign Up
          url: "/signup.html"
  footer:
    logo_img: images/logo_alt.png
    tagline: SaaS theme by Stackbit
    has_nav: true
    nav_title: Company
    has_social: true
    social_title: Community
    has_subscribe: true
    subscribe_title: Subscribe
    subscribe_content: Stay up to date with our latest developments.
    content: "&copy; Stackbit. All rights reserved."
    links:
      - text: Made with Stackbit
        url: "https://www.stackbit.com"
        new_window: true
sass:
  input_file: sass/main.scss.njk
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
